baseURL = "https://waluiki.ru"
languageCode = "ru-ru"
title = "Обретенная память"
theme = "book"
enableemoji = "true"
publishDir = "public_html"

[params]
  BookToC = "true"
  BookLogo = 'logo.svg'
  BookMenuBundle = '/menu'
